/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>


typedef char fax_record[80];
bool_t xdr_fax_record();

struct transfer_info {
	char filename[80];
	char filebuf[512];
	int file_flag;
};
typedef struct transfer_info transfer_info;
bool_t xdr_transfer_info();

#define FAXPROG ((u_long)567891234)
#define FAXVERS ((u_long)1)
#define ADD_FAX_ENTRY ((u_long)1)
extern int *add_fax_entry_1();
#define FILE_TRANSFER ((u_long)2)
extern int *file_transfer_1();
