/*----------------------------------------------------------------------------
Program:	TEL_Mnemonics.h
Purpose:	To define a set of id numbers used by send_to_monitor.
Author:		George Wenzel
Date:		02/12/2001
Update:		03/08/2001 added TEL_PROMPTANDCOLLECT
Update:		04/13/2001 added TEL_DIALEXTENSION.
Update:		06/07/2002 added TEL_TTSSETPARAMETER.
Update:		07/08/2002 added TEL_REJECTCALL.
Update:		08/26/2002 added TEL_TRANSACTIONRECORD.
----------------------------------------------------------------------------*/
#ifndef TEL_MNEMONICS_H
#define TEL_MNEMONICS_H

#define TEL_API_BASE 1000

#define TEL_INITTELECOM		TEL_API_BASE+1
#define TEL_EXITTELECOM		TEL_API_BASE+2
#define TEL_ANSWERCALL		TEL_API_BASE+3
#define TEL_CLEARDTMF		TEL_API_BASE+4
#define TEL_COPYPHRASE		TEL_API_BASE+5
#define TEL_BRIDGECALL		TEL_API_BASE+6
#define TEL_DELETEPHRASE	TEL_API_BASE+7
#define TEL_ENDOFCALL		TEL_API_BASE+8
#define TEL_FILETOPHRASE	TEL_API_BASE+9
#define TEL_GETGLOBAL		TEL_API_BASE+10
#define TEL_GETGLOBALSTRING	TEL_API_BASE+11
#define TEL_LOADLANGUAGE	TEL_API_BASE+12
#define TEL_LOADVOCAB		TEL_API_BASE+13
#define TEL_INITIATECALL	TEL_API_BASE+14
#define TEL_INPUTDTMF		TEL_API_BASE+15
#define TEL_INPUTNUMBER		TEL_API_BASE+16
#define TEL_INPUTPHRASE		TEL_API_BASE+17
#define TEL_INPUTVOICE		TEL_API_BASE+18
#define TEL_ISDNHOLDPHRASE	TEL_API_BASE+19
#define TEL_OUTPUTDTMF		TEL_API_BASE+20
#define TEL_OUTPUTPHRASE	TEL_API_BASE+21
#define TEL_PORTOPERATION	TEL_API_BASE+22
#define TEL_OUTPUTTTS		TEL_API_BASE+23
#define TEL_PHRASELENGTH	TEL_API_BASE+24
#define TEL_PHRASETOFILE	TEL_API_BASE+25
#define TEL_RECVFAX		TEL_API_BASE+26
#define TEL_SENDFAX		TEL_API_BASE+27
#define TEL_SETGLOBAL		TEL_API_BASE+28
#define TEL_SETHOOK		TEL_API_BASE+29
#define TEL_TRANSFERCALL	TEL_API_BASE+30

#define TEL_STARTPARTIALFAX	TEL_API_BASE+31
#define TEL_ADDTOPARTIALFAX	TEL_API_BASE+32
#define TEL_ENDPARTIALFAX	TEL_API_BASE+33
#define TEL_SPEAKSYSTEMPHRASE	TEL_API_BASE+34
#define TEL_SCHEDULEFAX		TEL_API_BASE+35
#define TEL_SPEAKPHRASE		TEL_API_BASE+36
#define TEL_SPEAKPHRASEFILE	TEL_API_BASE+37
#define TEL_PORTSTATUS		TEL_API_BASE+38
#define TEL_STARTNEWAPP		TEL_API_BASE+39
#define TEL_SETGLOBALSTRING	TEL_API_BASE+40
#define TEL_SPEAKTTS		TEL_API_BASE+41
#define TEL_SCHEDULECALL	TEL_API_BASE+42
#define TEL_UNSCHEDULECALL	TEL_API_BASE+43
#define TEL_GETCDFINFO		TEL_API_BASE+44

#define TEL_GETINPUT		TEL_API_BASE+45
#define TEL_RECORDPHRASE	TEL_API_BASE+46
#define TEL_SPEAKFILE		TEL_API_BASE+47
#define TEL_ISDNHOLDINPUT	TEL_API_BASE+48
#define TEL_DROPCALL		TEL_API_BASE+49
#define TEL_GETDTMF		TEL_API_BASE+50
#define TEL_SPEAK		TEL_API_BASE+51
#define TEL_RECORD		TEL_API_BASE+52

#define TEL_PROMPTANDCOLLECT	TEL_API_BASE+53
#define TEL_LOADTAGS			TEL_API_BASE+54
#define TEL_SAVETAGS			TEL_API_BASE+55

#define TEL_SENDINFOELEMENTS		TEL_API_BASE+56
#define TEL_GETINFOELEMENTS		TEL_API_BASE+57

#define TEL_DIALEXTENSION		TEL_API_BASE+58
#define TEL_TTSSETPARAMETER		TEL_API_BASE+59


#define TEL_REJECTCALL			TEL_API_BASE+60 

#define TEL_TRANSACTIONRECORD	TEL_API_BASE+61 

#define TEL_BLASTDIAL			TEL_API_BASE+77
#endif
