#ifndef ARC_SIP_CODECS_DOT_H
#define ARC_SIP_CODECS_DOT_H

enum arc_codec_lookup_e {
  ARC_AUDIO_CODEC_G711A_8K = 0,
  ARC_AUDIO_CODEC_G711U_8K,
  // g729 
  ARC_AUDIO_CODEC_G729_8K,
  // silk codec 
  ARC_AUDIO_CODEC_SILK_8K,
  ARC_AUDIO_CODEC_SILK_12K,
  ARC_AUDIO_CODEC_SILK_16K,
  ARC_AUDIO_CODEC_SILK_24K,
  // 
  ARC_AUDIO_CODEC_END
};

#endif

