#----------------------------------------------------------------------------
# Program:	Makefile
# Purpose:	Master make file for Dialogic Fax.
# Author:	George Wenzel
# Date:		01/19/98 
#----------------------------------------------------------------------------

all: Always
	( cd ./src; 	make all )

clean: Always
	( cd ./src; 	make clean )

Always:
