CC=gcc  

#TEL_GetGlobalByInt.c
#NetworkTransfer_Common.c\

SOURCES=\
answercall.c\
arcavb.c\
FAX_Common.c\
get_uniq_filename.c\
ocmNTUtil.c\
ocmUtil.c\
stubs.c\
TEL_AnswerCall.c\
TEL_BlastDial.c\
TEL_BridgeCall.c\
TEL_BridgeThirdLeg.c\
TEL_BuildFaxList.c\
TEL_ClearDTMF.c\
TEL_Common_blastDial.c\
TEL_Common.c\
TEL_ConfAddUser.c\
TEL_ConferenceStart.c\
TEL_ConferenceStop.c\
TEL_ConfRemoveUser.c\
TEL_ConfSendData.c\
TEL_DialExtension.c\
TEL_DropCall.c\
TEL_ExitTelecom.c\
TEL_FindMe.c\
TEL_GetCDFInfo.c\
TEL_GetDTMF.c\
TEL_GetGlobal.c\
TEL_GetGlobalStringByInt.c\
TEL_GetGlobalString.c\
TEL_GetMsgFromApp.c\
TEL_HoldCall.c\
TEL_InitiateCall.c\
TEL_InitTelecom.c\
TEL_ListenCall.c\
TEL_LoadTags.c\
TELmsg.c\
TEL_OutputDTMF.c\
TEL_PlayMedia.c\
TEL_PortOperation.c\
TEL_PromptAndCollect.c\
TEL_Record.c\
TEL_RecordMedia.c\
TEL_RecordSrgs.c\
TEL_RecvFax.c\
TEL_RejectCall.c\
TEL_Rest.c\
TEL_RetrieveCall.c\
TEL_SaveTags.c\
TEL_ScheduleCall.c\
TEL_ScheduleFax.c\
TEL_ScheduleNTCall.c\
TEL_SendFax.c\
TEL_SendMsgToApp.c\
TEL_SetGlobalByInt.c\
TEL_SetGlobal.c\
TEL_SetGlobalStringByInt.c\
TEL_SetGlobalString.c\
TEL_Speak.c\
TEL_SpeakTTS.c\
TEL_SRAddWords.c\
TEL_SRDeleteWords.c\
TEL_SRExit.c\
TEL_SRGetParameter.c\
TEL_SRGetPhoneticSpelling.c\
TEL_SRGetResult.c\
TEL_SRGetXMLResult.c\
TEL_SRInit.c\
TEL_SRLearnWord.c\
TEL_SRLoadGrammar.c\
TEL_SRLogEvent.c\
TEL_SRRecognize.c\
TEL_SRRecognizeV2.c\
TEL_SRReleaseResource.c\
TEL_SRReserveResource.c\
TEL_SRSetParameter.c\
TEL_SRUnloadGrammar.c\
TEL_SRUnloadGrammars.c\
TEL_StartNewApp.c\
TEL_TransferCall.c\
TEL_TTSGetParameter.c\
TEL_TTSSetParameter.c\
TEL_UnscheduleCall.c\

INCLUDES=\
	-I../include \
	-I../Common/include \


all:  
	$(CC) -c $(SOURCES) $(INCLUDES)  


clean:	
	rm -f *.o 

lib: 

	ar -cru libISPtel.a  *.o 





