#----------------------------------------------------------------------------
# Program:	Makefile
# Purpose:	
# Author:	Aumtech, Inc
#----------------------------------------------------------------------------
all: Always
	make -f Makefile.eXosip4.1 all
	rm *.o

clean: Always
	make -f Makefile.eXosip4.1 clean

Always:
