/*----------------------------------------------------------------------------
Program:	TEL_SendToMonitor.h
Purpose:	To define a set of id numbers used by send_to_monitor.
Author:		George Wenzel
Date:		10/18/2000
Update:	07/16/2001 APJ Added TEL_PROMPTANDCOLLECT, TEL_LOADTAGS, TEL_SAVETAGS.
Update:	08/02/2001 APJ Added TEL_DIALEXTENSION define.
Update: 07/22/2009 RG Added TEL_LISTENCALL define.
Update: 06/22/2010 djb Added TEL_BLASTDIAL define.
Update: 11/10/2012 djb Added Network Transfer defines
----------------------------------------------------------------------------*/
#ifndef TEL_SENDTOMONITOR_H
#define TEL_SENDTOMONITOR_H

#define TEL_API_BASE 1000

#define TEL_INITTELECOM		TEL_API_BASE+1
#define TEL_EXITTELECOM		TEL_API_BASE+2
#define TEL_ANSWERCALL		TEL_API_BASE+3
#define TEL_CLEARDTMF		TEL_API_BASE+4
#define TEL_COPYPHRASE		TEL_API_BASE+5
#define TEL_BRIDGECALL		TEL_API_BASE+6
#define TEL_DELETEPHRASE	TEL_API_BASE+7
#define TEL_ENDOFCALL		TEL_API_BASE+8
#define TEL_FILETOPHRASE	TEL_API_BASE+9
#define TEL_GETGLOBAL		TEL_API_BASE+10
#define TEL_GETGLOBALSTRING	TEL_API_BASE+11
#define TEL_LOADLANGUAGE	TEL_API_BASE+12
#define TEL_LOADVOCAB		TEL_API_BASE+13
#define TEL_INITIATECALL	TEL_API_BASE+14
#define TEL_INPUTDTMF		TEL_API_BASE+15
#define TEL_INPUTNUMBER		TEL_API_BASE+16
#define TEL_INPUTPHRASE		TEL_API_BASE+17
#define TEL_INPUTVOICE		TEL_API_BASE+18
#define TEL_ISDNHOLDPHRASE	TEL_API_BASE+19
#define TEL_OUTPUTDTMF		TEL_API_BASE+20
#define TEL_OUTPUTPHRASE	TEL_API_BASE+21
#define TEL_PORTOPERATION	TEL_API_BASE+22
#define TEL_OUTPUTTTS		TEL_API_BASE+23
#define TEL_PHRASELENGTH	TEL_API_BASE+24
#define TEL_PHRASETOFILE	TEL_API_BASE+25
#define TEL_RECVFAX			TEL_API_BASE+26
#define TEL_SENDFAX			TEL_API_BASE+27
#define TEL_SETGLOBAL		TEL_API_BASE+28
#define TEL_SETHOOK			TEL_API_BASE+29
#define TEL_TRANSFERCALL	TEL_API_BASE+30

#define TEL_STARTPARTIALFAX	TEL_API_BASE+31
#define TEL_ADDTOPARTIALFAX	TEL_API_BASE+32
#define TEL_ENDPARTIALFAX	TEL_API_BASE+33
#define TEL_SPEAKSYSTEMPHRASE	TEL_API_BASE+34
#define TEL_SCHEDULEFAX		TEL_API_BASE+35
#define TEL_SPEAKPHRASE		TEL_API_BASE+36
#define TEL_SPEAKPHRASEFILE	TEL_API_BASE+37
#define TEL_PORTSTATUS		TEL_API_BASE+38
#define TEL_STARTNEWAPP		TEL_API_BASE+39
#define TEL_SETGLOBALSTRING	TEL_API_BASE+40
#define TEL_SPEAKTTS		TEL_API_BASE+41
#define TEL_SCHEDULECALL	TEL_API_BASE+42
#define TEL_UNSCHEDULECALL	TEL_API_BASE+43
#define TEL_GETCDFINFO		TEL_API_BASE+44

#define TEL_GETINPUT		TEL_API_BASE+45
#define TEL_RECORDPHRASE	TEL_API_BASE+46
#define TEL_SPEAKFILE		TEL_API_BASE+47
#define TEL_ISDNHOLDINPUT	TEL_API_BASE+48
#define TEL_DROPCALL		TEL_API_BASE+49
#define TEL_GETDTMF			TEL_API_BASE+50
#define TEL_SPEAK			TEL_API_BASE+51
#define TEL_RECORD			TEL_API_BASE+52

#define TEL_PROMPTANDCOLLECT    TEL_API_BASE+53
#define TEL_LOADTAGS            TEL_API_BASE+54
#define TEL_SAVETAGS            TEL_API_BASE+55
#define TEL_DIALEXTENSION       TEL_API_BASE+56

#define TEL_TTSSETPARAMETER     TEL_API_BASE+59
#define TEL_REJECTCALL          TEL_API_BASE+60

#define TEL_TTSGETPARAMETER     TEL_API_BASE+62
#define TEL_PLAYMEDIA     		TEL_API_BASE+63
#define TEL_RECORDMEDIA     	TEL_API_BASE+64
#define TEL_FINDME     			TEL_API_BASE+65
#define TEL_HOLDCALL            TEL_API_BASE+66
#define TEL_RETRIEVECALL        TEL_API_BASE+67
#define TEL_SENDINFOELEMENTS    TEL_API_BASE+68
#define TEL_GETINFOELEMENTS     TEL_API_BASE+69


#define TEL_LISTENCALL          TEL_API_BASE+70
#define TEL_BUILDFAXLIST          TEL_API_BASE+71
#define TEL_CONFERENCESTART		TEL_API_BASE+72
#define TEL_CONFERENCESTOP		TEL_API_BASE+73
#define TEL_CONFERENCEADDUSER	TEL_API_BASE+74
#define TEL_CONFERENCEREMOVEUSER	TEL_API_BASE+75
#define TEL_CONFERENCESENDDATA		TEL_API_BASE+76
#define TEL_BLASTDIAL			TEL_API_BASE+77

#define TEL_SCHEDULENTCALL      TEL_API_BASE+78
#define TEL_SENDMSGTOAPP        TEL_API_BASE+79
#define TEL_GETMSGFROMAPP       TEL_API_BASE+80

#define ARCAVB_VERIFYCONTINUOUS	TEL_API_BASE+81
#define TEL_TTSRELEASERESOURCE  TEL_API_BASE+82

#endif
